package utils;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import reports.ExtentTestManager;

public final class FrameworkLogger {

    private static final Logger logger =
            LogManager.getLogger(
                    FrameworkLogger.class);

    /*
     * During keyword execution, PASS/FAIL messages
     * are temporarily stored here.
     *
     * Why?
     *
     * Because the keyword executes first and the screenshot
     * is captured immediately after the keyword.
     *
     * Therefore we cannot create the Extent row immediately.
     */
    private static final ThreadLocal<String> LAST_PASS_MESSAGE =
            new ThreadLocal<>();

    private static final ThreadLocal<String> LAST_FAIL_MESSAGE =
            new ThreadLocal<>();

    /*
     * Indicates whether a keyword is currently executing.
     */
    private static final ThreadLocal<Boolean> KEYWORD_EXECUTION =
            ThreadLocal.withInitial(() -> false);

    private FrameworkLogger() {
    }

    // ==========================================================
    // Caller Information
    // ==========================================================

    /*
     * Returns the Java class that actually called FrameworkLogger.
     */
    private static String getCallerClass() {

        StackTraceElement[] stackTrace =
                Thread.currentThread().getStackTrace();

        for (StackTraceElement element : stackTrace) {

            String className =
                    element.getClassName();

            if (!className.equals(
                    FrameworkLogger.class.getName())
                    && !className.equals(
                    Thread.class.getName())) {

                String simpleClassName =
                        className.substring(
                                className.lastIndexOf('.') + 1);

                return "["
                        + simpleClassName
                        + ".java:"
                        + element.getLineNumber()
                        + "]";
            }
        }

        return "[Unknown.java]";
    }

    // ==========================================================
    // Keyword Execution Context
    // ==========================================================

    /*
     * Called BEFORE executing a keyword.
     *
     * Clears any previous keyword messages.
     */
    public static void startKeywordExecution() {

        KEYWORD_EXECUTION.set(true);

        LAST_PASS_MESSAGE.remove();
        LAST_FAIL_MESSAGE.remove();
    }

    /*
     * Called AFTER the keyword and Extent logging are completed.
     */
    public static void endKeywordExecution() {

        KEYWORD_EXECUTION.remove();

        LAST_PASS_MESSAGE.remove();
        LAST_FAIL_MESSAGE.remove();
    }

    /*
     * Returns the PASS message generated by the keyword.
     */
    public static String getLastPassMessage() {

        return LAST_PASS_MESSAGE.get();
    }

    /*
     * Returns the FAIL message generated by the keyword.
     */
    public static String getLastFailMessage() {

        return LAST_FAIL_MESSAGE.get();
    }

    // ==========================================================
    // Generic Log Methods
    // ==========================================================

    // INFO

    public static void info(String message) {

        logger.info(
                getCallerClass()
                        + " [INFO] "
                        + message);

        ExtentTestManager.info(message);

        AllureManager.logInfo(message);
    }

    // STEP

    public static void step(String message) {

        logger.info(
                getCallerClass()
                        + " [STEP] "
                        + message);

        /*
         * Do not buffer normal framework steps.
         */
        ExtentTestManager.info(
                "STEP : " + message);

        AllureManager.step(message);
    }

    // PASS

    public static void pass(String message) {

        logger.info(
                getCallerClass()
                        + " [PASS] "
                        + message);

        /*
         * During keyword execution:
         *
         * DO NOT create Extent row yet.
         *
         * KeywordExecutor will capture screenshot first
         * and then create ONE combined row.
         */
        if (KEYWORD_EXECUTION.get()) {

            LAST_PASS_MESSAGE.set(message);

        } else {

            /*
             * Normal framework PASS message.
             */
            ExtentTestManager.pass(message);
        }

        AllureManager.logPass(message);
    }

    // FAIL

    public static void fail(String message) {

        logger.error(
                getCallerClass()
                        + " [FAIL] "
                        + message);

        /*
         * During keyword execution:
         *
         * Store the failure message.
         *
         * KeywordExecutor will attach the failure screenshot
         * and create the final Extent row.
         */
        if (KEYWORD_EXECUTION.get()) {

            LAST_FAIL_MESSAGE.set(message);

        } else {

            ExtentTestManager.fail(message);
        }

        AllureManager.logFail(message);
    }

    // ERROR - Message Only

    public static void error(String message) {

        logger.error(
                getCallerClass()
                        + " [ERROR] "
                        + message);

        /*
         * ERROR is not a keyword PASS/FAIL result.
         */
        ExtentTestManager.fail(message);

        AllureManager.logError(message);
    }

    // ERROR - Message + Exception

    public static void error(
            String message,
            Throwable throwable) {

        logger.error(
                getCallerClass()
                        + " [ERROR] "
                        + message,
                throwable);

        ExtentTestManager.fail(message);

        AllureManager.logError(
                message,
                throwable);
    }

    // WARNING

    public static void warn(String message) {

        logger.warn(
                getCallerClass()
                        + " [WARN] "
                        + message);

        ExtentTestManager.warning(message);

        AllureManager.logWarn(message);
    }

    // DEBUG

    public static void debug(String message) {

        logger.debug(
                getCallerClass()
                        + " [DEBUG] "
                        + message);

        AllureManager.logDebug(message);
    }

    // ==========================================================
    // Keyword Specific Log Methods
    // ==========================================================

    public static void browserOpened(
            String browser) {

        pass(
                browser
                        + " Browser Opened Successfully.");
    }

    public static void browserClosed() {

        pass(
                "Browser Closed Successfully.");
    }

    public static void urlLaunched(
            String url) {

        pass(
                "URL Launched Successfully. URL : "
                        + url);
    }

    public static void valueEntered(
            String field,
            String value) {

        pass(
                field
                        + " Entered Successfully. Value : "
                        + value);
    }

    public static void elementClicked(
            String element) {

        pass(
                element
                        + " Clicked Successfully.");
    }

    public static void elementCleared(
            String element) {

        pass(
                element
                        + " Cleared Successfully.");
    }

    public static void keyPressed(
            String key) {

        pass(
                key
                        + " Key Pressed.");
    }
}